sudo: required
language: python

services:
  - docker

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"

install:
  - python setup.py install
  - pip install -Ur requirements.txt
  - pip install codecov

script:
  - make cov-ci
  - python setup.py check -ms

env:
  global:
    - PYTHON=python
  matrix:
    - PYTHONASYNCIODEBUG=x
    - PYTHONASYNCIODEBUG=

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_script:
  - codecov

deploy:
  provider: pypi
  user: virmir49
  password:
    secure: $PYPY_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5